import type { Metadata } from "next";
import { Lato, Poppins } from "next/font/google";
import "./globals.css";

export const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"], // Ajoute les poids que tu veux
  variable: "--font-lato", // si tu veux les utiliser en CSS
  display: "swap",
});

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr-FR">
      <body className={`${lato.variable} ${poppins.variable}`}>{children}</body>
    </html>
  );
}
